import img1 from '../../../assets/images/users/1.jpg';
import img2 from '../../../assets/images/users/2.jpg';
import img3 from '../../../assets/images/users/3.jpg';
import img4 from '../../../assets/images/users/4.jpg';
import img5 from '../../../assets/images/users/5.jpg';

const Users = [
  {
    imgsrc: img4,
    name: 'Muskan Agrawal',
    email: 'MCPA@gmail.com',
    pname: 'Talent',
    ApprovedBy: "superAdmin",
    createdOn: "13/06/2020",
    status: 'Active',
    weeks: '40',
    budget: '2.4',
  },
  {
    imgsrc: img1,
    name: 'Payal Thakkar',
    email: 'pt@gmail.com',
    pname: 'Talent',
    ApprovedBy: "superAdmin",
    createdOn: "13/06/2020",
    status: 'Active',
    weeks: '11',
    budget: '3.9',
  },
  {
    imgsrc: img2,
    name: 'Pankti Bhavsar',
    email: 'Pb@gmail.com',
    pname: 'Client',
    ApprovedBy: "superAdmin",
    createdOn: "13/06/2020",
    status: 'Pending',
    weeks: '19',
    budget: '24.5',
  },
  {
    imgsrc: img3,
    name: 'Rahul Pratap Singh',
    email: 'rp@gmail.com',
    pname: 'Admin',
    ApprovedBy: "superAdmin",
    createdOn: "13/06/2020",
    status: 'Completed',
    weeks: '30',
    budget: '12.8',
  },

  {
    imgsrc: img5,
    name: 'Vidish Shah',
    email: 'vs@gmail.com',
    pname: 'Admin',
    ApprovedBy: "superAdmin",
    createdOn: "13/06/2020",
    status: 'Cancel',
    weeks: '1',
    budget: '9.3',
  },
  {
    imgsrc: img4,
    name: 'Nirav Joshi',
    email: 'nirav@gmail.com',
    pname: 'Talent',
    ApprovedBy: "superAdmin",
    createdOn: "13/06/2020",
    status: 'Active',
    weeks: '16',
    budget: '2.4',
  },
  {
    imgsrc: img1,
    name: 'Sunil Joshi',
    email: 'sunil@gmail.com',
    pname: 'BD',
    ApprovedBy: "superAdmin",
    createdOn: "13/06/2020",
    status: 'Active',
    weeks: '12',
    budget: '3.9',
  },
  {
    imgsrc: img2,
    name: 'Andrew McDownland',
    email: 'andrew@gmail.com',
    pname: 'Admin',
    ApprovedBy: "superAdmin",
    createdOn: "13/06/2020",
    status: 'Pending',
    weeks: '14',
    budget: '24.5',
  },
  {
    imgsrc: img3,
    name: 'Christopher Jamil',
    email: 'jamil@gmail.com',
    pname: 'Talent',
    ApprovedBy: "superAdmin", 
    createdOn: "13/06/2020",
    status: 'Completed',
    weeks: '12',
    budget: '12.8',
  },

  {
    imgsrc: img5,
    name: 'Micheal Doe',
    email: 'micheal@gmail.com',
    pname: 'Admin',
    ApprovedBy: "superAdmin",
    createdOn: "13/06/2020",
    status: 'Cancel',
    weeks: '9',
    budget: '9.3',
  },
];

export default Users;